export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { ThemeProvider } from '@/components/ui/theme-provider'


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider  attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>{children}</ThemeProvider>
      </body>
    </html>
  )
}
